name: flutter_native_admob
description: Plugin to integrate Firebase Native Admob to Flutter application. Both iOS and Android supported
version: 2.2.0
homepage: https://github.com/duyduong/flutter_native_admob

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.nover.flutternativeadmob
    pluginClass: FlutterNativeAdmobPlugin
